(()=>{'use strict';
const D=window.DERIVA_DATA,app=document.querySelector('#app');
const S={view:(location.hash.slice(1)||'ahora').split('/')[0],story:0,edition:0,drift:null,history:[],saved:[],panel:false,modal:null,query:'',filter:'todo',distance:55,session:12,route:'inicio documental'};
const all=()=>[...D.news,...D.archive];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const valid=u=>{try{const x=new URL(u);return ['http:','https:'].includes(x.protocol)?x.href:'#'}catch{return '#'}};
const fmt=(n,t)=>String(n+1).padStart(2,'0')+' / '+String(t).padStart(2,'0');
function db(){return new Promise((ok,no)=>{const r=indexedDB.open('deriva-xpan',3);r.onupgradeneeded=()=>{const x=r.result;['saved','history','prefs'].forEach(k=>{if(!x.objectStoreNames.contains(k))x.createObjectStore(k,{keyPath:'id'})})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function getAll(store){try{const x=await db();return await new Promise(ok=>{const r=x.transaction(store).objectStore(store).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>ok([])})}catch{return[]}}
async function put(store,value){const x=await db();return new Promise(ok=>{const r=x.transaction(store,'readwrite').objectStore(store).put(value);r.onsuccess=()=>ok();r.onerror=()=>ok()})}
async function del(store,id){const x=await db();return new Promise(ok=>{const r=x.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>ok();r.onerror=()=>ok()})}
function shell(content){return `<div class="shell"><header class="topbar"><div class="mark">deriva <span>/ xpan</span></div><div class="topmeta"><span><i class="status-dot"></i>corte documental</span><span>${esc(D.editions[S.edition].slot)}</span></div><button class="iconbtn" data-do="panel" aria-label="abrir información y ajustes">⌁</button></header><main id="main" class="stage">${content}</main><nav class="nav" aria-label="navegación principal">${[['ahora','01'],['deriva','02'],['archivo','03']].map(([v,n])=>`<button data-view="${v}" class="${S.view===v?'active':''}">${n}<b>${v}</b></button>`).join('')}</nav></div>${S.panel?panel():''}${S.modal?modal():''}`}
function visual(item,index,total){const img=item.image?`<img src="${esc(valid(item.image))}" alt="${esc(item.title)}" loading="${index?'lazy':'eager'}" onerror="this.remove();this.parentElement.classList.add('noimage')">`:'';return `<div class="visual ${esc(item.layout||'')} ${item.image?'':'noimage'}">${img}<div class="diagram" aria-hidden="true"></div><div class="diagram-index"><span>${esc(item.kind)}</span><span>${esc(item.institution)}</span></div><span class="visual-label">${esc(item.date||item.category)}</span>${total?`<span class="counter">${fmt(index,total)}</span>`:''}<span class="caption">${esc(item.credit)}</span></div>`}
function now(){const ed=D.editions[S.edition],items=ed.items.map(id=>D.news.find(x=>x.id===id)).filter(Boolean),x=items[S.story%items.length];return `<article class="story" data-swipe>${visual(x,S.story,items.length)}<section class="copy"><div class="progress"><i style="width:${((S.story+1)/items.length)*100}%"></i></div><div class="eyebrow"><span>${esc(x.category)} · ${esc(x.time)}</span><span class="state">${esc(x.status)}</span></div><h1 class="headline">${esc(x.title)}</h1><p class="summary">${esc(x.summary)}</p><p class="why">por qué importa — ${esc(x.why)}</p><div class="actions"><button class="action" data-do="prev">← anterior</button><button class="action" data-do="next">siguiente →</button><button class="action" data-do="save" data-id="${x.id}">${S.saved.includes(x.id)?'guardado':'guardar'}</button><button class="action primary" data-do="cross" data-id="${x.id}">abrir antecedente</button><button class="action" data-do="sources" data-id="${x.id}">fuentes [${x.sources.length}]</button><button class="action" data-do="share" data-id="${x.id}">compartir</button><a class="action" style="display:grid;place-items:center;color:inherit;text-decoration:none" href="${valid(x.url)}" target="_blank" rel="noopener">abrir origen ↗</a><button class="action" data-do="editions">ediciones</button></div></section></article>`}
const tokens=x=>new Set([...(x.topics||[]),...(x.entities||[]),...(x.operations||[]),...(x.materials||[])].map(v=>v.toLowerCase()));
function overlap(a,b){const A=tokens(a),B=tokens(b);return [...A].filter(x=>B.has(x)).length}
function candidate(current,op){let pool=all().filter(x=>x.id!==current.id&&!S.history.includes(x.id));if(!pool.length){S.history=[];pool=all().filter(x=>x.id!==current.id)}const scored=pool.map((x,i)=>{let q=overlap(current,x)*12;const news=x.kind==='noticia';if(op==='seguir')q+=overlap(current,x)*14;if(op==='acercar')q+=(x.topics||[]).some(t=>['infraestructura','territorio','estructura','mecanismo','fabricación'].includes(t))*18;if(op==='alejar')q=40-overlap(current,x)*10+Math.abs((x.date||'').length-(current.date||'').length);if(op==='profundizar')q+=(['paper','patente','mapa','pdf','libro'].includes(x.kind)?28:0)+overlap(current,x)*8;if(op==='otra')q=(i*17+S.history.length*13)%31-overlap(current,x)*2;if(op==='cruzar')q+=(news!== (current.kind==='noticia')?35:-30)+overlap(current,x)*16;return{x,q}}).sort((a,b)=>b.q-a.q);return scored[0]?.x||pool[0]}
function drift(){const x=S.drift||D.archive[0];return `<article class="deriva" data-swipe>${visual(x,0,0)}<section class="fieldcopy"><div class="eyebrow"><span>${esc(x.kind)} · ${esc(x.institution)}</span><span>distancia ${S.distance}</span></div><h1 class="headline">${esc(x.title)}</h1><p class="summary">${esc(x.summary)}</p><p class="route">llegaste aquí por: ${esc(S.route)}</p><div class="ops"><button data-op="seguir"><strong>seguir</strong>relación semántica</button><button data-op="acercar"><strong>acercar</strong>perfil local</button><button data-op="alejar"><strong>alejar</strong>otra región del campo</button><button data-op="profundizar"><strong>profundizar</strong>fuente técnica</button><button data-op="cruzar"><strong>cruzar</strong>archivo ↔ ahora</button><button data-op="otra"><strong>otra cosa</strong>ruptura controlada</button><button data-do="save" data-id="${x.id}"><strong>${S.saved.includes(x.id)?'guardado':'guardar'}</strong>archivo local</button><button data-do="share" data-id="${x.id}"><strong>compartir</strong>enlace</button><a href="${valid(x.url)}" target="_blank" rel="noopener" style="color:inherit;text-decoration:none"><strong>abrir fuente ↗</strong>origen</a></div></section></article>`}
function cross(a,b){return `<article class="cross"><section class="cross-half">${a.image?`<img src="${valid(a.image)}" alt="">`:''}<span class="eyebrow">ahora · ${esc(a.category)}</span><h2>${esc(a.title)}</h2><small>${esc(a.institution)}</small></section><section class="cross-half">${b.image?`<img src="${valid(b.image)}" alt="">`:''}<span class="eyebrow">archivo · ${esc(b.kind)}</span><h2>${esc(b.title)}</h2><small>${esc(b.institution)}</small></section><div class="bridge">puente verificable — ${esc(bridge(a,b))} <button class="textbtn" data-view="deriva" style="float:right">continuar →</button></div></article>`}
function bridge(a,b){const shared=[...tokens(a)].filter(x=>tokens(b).has(x));return shared.length?`${a.title} → ${shared.slice(0,2).join(' + ')} → ${b.title}`:`${a.operations?.[0]||a.topics?.[0]} cambia de escala y conduce a ${b.operations?.[0]||b.topics?.[0]}`}
function archive(){const records=S.saved.map(id=>all().find(x=>x.id===id)).filter(Boolean);const base=S.filter==='guardados'?records:all();const q=S.query.toLowerCase();const items=base.filter(x=>(x.title+' '+x.summary+' '+x.institution+' '+(x.topics||[]).join(' ')).toLowerCase().includes(q));return `<section class="archive"><header class="archive-head"><div class="eyebrow"><span>archivo local / ${records.length} guardados</span><button class="textbtn" data-do="manage">importar · exportar</button></div><h1>campo acumulado</h1><div class="search"><input id="search" type="search" value="${esc(S.query)}" placeholder="buscar título, tema, fuente…" aria-label="buscar"><select id="filter" aria-label="filtrar"><option value="todo" ${S.filter==='todo'?'selected':''}>todo</option><option value="guardados" ${S.filter==='guardados'?'selected':''}>guardados</option></select></div></header><div class="archive-list">${items.length?items.map((x,i)=>`<article class="row" data-open="${x.id}" tabindex="0"><span class="row-index">${String(i+1).padStart(3,'0')}<br>${esc(x.kind)}</span><div><h2>${esc(x.title)}</h2><p>${esc(x.institution)} · ${esc(x.date)}</p></div><span class="arrow">↗</span></article>`).join(''):'<div class="empty">no hay registros en este corte.<br>guarda una pieza o cambia el filtro.</div>'}</div></section>`}
function panel(){return `<aside class="panel" role="dialog" aria-modal="true" aria-label="información"><div class="panelbox"><div class="paneltop"><b>deriva / sistema</b><button class="close" data-do="panel" aria-label="cerrar">×</button></div><h2>un instrumento para salir del flujo.</h2><section><label>distancia documental · ${S.distance}</label><input id="distance" type="range" min="0" max="100" value="${S.distance}"><label style="margin-top:16px">longitud de sesión</label><select id="session"><option>8</option><option selected>12</option><option>16</option></select></section><section><div class="panel-actions"><button data-do="install">instalar</button><button data-do="clearprofile">borrar perfil</button></div></section><section><label>ediciones conservadas offline</label>${D.editions.map((e,i)=>`<button class="editionline textbtn" data-edition="${i}"><b>${e.slot}</b><span>${e.date} · ${e.name}<br>${e.changed}</span><span>→</span></button>`).join('')}</section><section><label>estado de fuentes</label>${D.health.map(x=>`<div class="healthline"><b>${esc(x[2])}</b><span>${esc(x[0])}</span><span>${esc(x[1])}</span></div>`).join('')}</section><section><label>privacidad</label><p style="font:11px/1.5 var(--mono)">Sin cuenta ni telemetría. Guardados, notas, historial y preferencias permanecen en este dispositivo. Las fuentes externas sólo reciben la visita cuando decides abrirlas.</p></section></div></aside>`}
function modal(){const m=S.modal;if(m.type==='install')return `<div class="modal" role="dialog" aria-modal="true"><div class="modalbox"><div class="paneltop"><b>instalar en iphone</b><button class="close" data-do="close">×</button></div><h2>Safari → pantalla de inicio.</h2><ol class="installsteps"><li>abre esta página en Safari.</li><li>toca Compartir en la barra del navegador.</li><li>elige “Añadir a pantalla de inicio”.</li><li>confirma con “Añadir”.</li></ol></div></div>`;if(m.type==='sources'){const x=all().find(y=>y.id===m.id);return `<div class="modal" role="dialog" aria-modal="true"><div class="modalbox"><div class="paneltop"><b>procedencia</b><button class="close" data-do="close">×</button></div><h2>${esc(x.title)}</h2><p class="summary">${esc(x.credit)}</p><div class="source-links">${(x.sources||[x.institution]).map((s,i)=>`<a href="${valid(x.url)}" target="_blank" rel="noopener">${String(i+1).padStart(2,'0')} · ${esc(s)} ↗</a>`).join('')}</div></div></div>`}if(m.type==='manage')return `<div class="modal" role="dialog" aria-modal="true"><div class="modalbox"><div class="paneltop"><b>archivo local</b><button class="close" data-do="close">×</button></div><h2>mover sin entregar tus datos.</h2><div class="panel-actions"><button data-do="export">exportar JSON</button><label class="filelabel">importar JSON<input id="import" type="file" accept="application/json"></label></div></div></div>`;return''}
function render(){let c;if(S.view==='ahora')c=now();else if(S.view==='deriva')c=drift();else if(S.view==='archivo')c=archive();else if(S.view==='cruce'){const a=D.news[S.story%D.news.length],b=S.drift||candidate(a,'cruzar');c=cross(a,b)}else{S.view='ahora';c=now()}app.innerHTML=shell(c);bind()}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),1800)}
function nav(v){S.view=v;location.hash=v;render()}
async function save(id){if(S.saved.includes(id)){S.saved=S.saved.filter(x=>x!==id);await del('saved',id);toast('retirado del archivo')}else{S.saved.push(id);await put('saved',{id,at:new Date().toISOString()});toast('guardado en este dispositivo')}render()}
async function share(id){const x=all().find(y=>y.id===id);const data={title:x.title,text:x.summary,url:x.url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${x.title}\n${x.url}`);toast('enlace copiado')}}catch{}}
function operate(op){const current=S.drift||D.archive[0],next=candidate(current,op);S.history.push(current.id);S.drift=next;const shared=[...tokens(current)].filter(x=>tokens(next).has(x));S.route=op+' → '+(shared.slice(0,2).join(' + ')||`${current.kind} / ${next.kind}`);if(op==='cruzar'){const n=next.kind==='noticia'?next:candidate(next,'cruzar');S.story=Math.max(0,D.news.findIndex(x=>x.id===n.id));S.view='cruce';location.hash='cruce'}put('history',{id:next.id,at:new Date().toISOString(),operator:op});navigator.vibrate?.(12);render()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>nav(b.dataset.view));document.querySelectorAll('[data-do]').forEach(b=>b.onclick=async()=>{const a=b.dataset.do,id=b.dataset.id;if(a==='next'){const n=D.editions[S.edition].items.length;S.story=(S.story+1)%n;render()}if(a==='prev'){const n=D.editions[S.edition].items.length;S.story=(S.story-1+n)%n;render()}if(a==='save')save(id);if(a==='share')share(id);if(a==='cross'){const x=all().find(y=>y.id===id);S.drift=candidate(x,'cruzar');S.view='cruce';S.route=bridge(x,S.drift);location.hash='cruce';render()}if(a==='sources'){S.modal={type:'sources',id};render()}if(a==='panel'){S.panel=!S.panel;render()}if(a==='close'){S.modal=null;render()}if(a==='install'){S.modal={type:'install'};S.panel=false;render()}if(a==='editions'){S.panel=true;render()}if(a==='manage'){S.modal={type:'manage'};render()}if(a==='clearprofile'){S.history=[];await Promise.all((await getAll('history')).map(x=>del('history',x.id)));toast('perfil local borrado')}if(a==='export'){const blob=new Blob([JSON.stringify({schema:3,exportedAt:new Date().toISOString(),saved:S.saved},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='deriva-archivo.json';a.click();URL.revokeObjectURL(u)}});document.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>operate(b.dataset.op));document.querySelectorAll('[data-edition]').forEach(b=>b.onclick=()=>{S.edition=+b.dataset.edition;S.story=0;S.panel=false;nav('ahora')});document.querySelectorAll('[data-open]').forEach(r=>{const open=()=>{const x=all().find(y=>y.id===r.dataset.open);S.drift=x;S.route='archivo local → reabrir';nav('deriva')};r.onclick=open;r.onkeydown=e=>{if(e.key==='Enter')open()}});const q=document.querySelector('#search');if(q)q.oninput=e=>{S.query=e.target.value;archiveUpdate()};const f=document.querySelector('#filter');if(f)f.onchange=e=>{S.filter=e.target.value;render()};const dist=document.querySelector('#distance');if(dist)dist.oninput=e=>{S.distance=+e.target.value;dist.previousElementSibling.textContent='distancia documental · '+S.distance};const imp=document.querySelector('#import');if(imp)imp.onchange=importFile;swipe()}
function archiveUpdate(){const list=document.querySelector('.archive-list');if(!list)return;const q=S.query.toLowerCase(),base=S.filter==='guardados'?S.saved.map(id=>all().find(x=>x.id===id)).filter(Boolean):all(),items=base.filter(x=>(x.title+' '+x.summary+' '+x.institution+' '+(x.topics||[]).join(' ')).toLowerCase().includes(q));list.innerHTML=items.map((x,i)=>`<article class="row" data-open="${x.id}" tabindex="0"><span class="row-index">${String(i+1).padStart(3,'0')}<br>${esc(x.kind)}</span><div><h2>${esc(x.title)}</h2><p>${esc(x.institution)} · ${esc(x.date)}</p></div><span class="arrow">↗</span></article>`).join('')||'<div class="empty">sin coincidencias.</div>';bindRows()}
function bindRows(){document.querySelectorAll('[data-open]').forEach(r=>r.onclick=()=>{S.drift=all().find(y=>y.id===r.dataset.open);S.route='archivo local → reabrir';nav('deriva')})}
async function importFile(e){try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.saved))throw Error();for(const id of data.saved.filter(id=>all().some(x=>x.id===id))){if(!S.saved.includes(id))S.saved.push(id);await put('saved',{id,at:new Date().toISOString()})}S.modal=null;toast('archivo importado');render()}catch{toast('JSON no válido')}}
function swipe(){const el=document.querySelector('[data-swipe]');if(!el)return;let x=0,y=0;el.ontouchstart=e=>{x=e.touches[0].clientX;y=e.touches[0].clientY};el.ontouchend=e=>{const dx=e.changedTouches[0].clientX-x,dy=e.changedTouches[0].clientY-y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5){if(S.view==='ahora'){const n=D.editions[S.edition].items.length;S.story=(S.story+(dx<0?1:-1)+n)%n;render()}else operate(dx<0?'otra':'seguir')}}}
window.addEventListener('hashchange',()=>{const v=(location.hash.slice(1)||'ahora').split('/')[0];if(v!==S.view){S.view=v;render()}});window.addEventListener('keydown',e=>{if(e.key==='Escape'&&(S.modal||S.panel)){S.modal=null;S.panel=false;render()}if(S.view==='ahora'&&['ArrowLeft','ArrowRight'].includes(e.key)){const n=D.editions[S.edition].items.length;S.story=(S.story+(e.key==='ArrowRight'?1:-1)+n)%n;render()}});
async function init(){S.saved=(await getAll('saved')).map(x=>x.id);S.history=(await getAll('history')).map(x=>x.id);S.drift=D.archive[0];render();if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)toast('nueva versión lista · recarga')})})}).catch(()=>{})}}
init();
})();
