(()=>{'use strict';
const DATA=window.DERIVA_CORPUS,root=document.querySelector('#app'),canvas=document.querySelector('#field'),ctx=canvas.getContext('2d');
const state={portal:true,index:0,layer:'present',depth:0,saved:[],sheet:null,system:false,pulse:[],pulseState:'leyendo señales externas…'};
const byId=id=>DATA.archive.find(x=>x.id===id)||DATA.present.find(x=>x.id===id);
const current=()=>{const p=DATA.present[state.index];return state.layer==='present'?p:byId(p.excavate[state.depth%p.excavate.length])};
const safe=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const url=u=>{try{const x=new URL(u);return /^https?:$/.test(x.protocol)?x.href:'#'}catch{return'#'}};
const pos=n=>{n=n%12;return `${(n%4)*33.333}% ${Math.floor(n/4)*50}%`};
const atlas=n=>n>=12?'./assets/atlas-field-02.webp':'./assets/atlas.webp';
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open('deriva-xpan',4);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('saved'))d.createObjectStore('saved',{keyPath:'id'});if(!d.objectStoreNames.contains('history'))d.createObjectStore('history',{keyPath:'key'});if(!d.objectStoreNames.contains('prefs'))d.createObjectStore('prefs',{keyPath:'id'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function dbAll(store){try{const d=await openDB();return await new Promise(ok=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>ok([])})}catch{return[]}}
async function dbPut(store,value){try{const d=await openDB();await new Promise(ok=>{const r=d.transaction(store,'readwrite').objectStore(store).put(value);r.onsuccess=r.onerror=()=>ok()})}catch{}}
async function dbDelete(store,id){try{const d=await openDB();await new Promise(ok=>{const r=d.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=r.onerror=()=>ok()})}catch{}}
function portal(){return `<main class="portal" id="content"><div class="plate"></div><div class="vignette"></div><section class="portal-copy"><h1 class="portal-mark">deriva</h1><p>un canal entre lo que está alterando el mundo ahora y las formas que lo hicieron posible.</p><small>${safe(DATA.meta.edition)} · ${safe(DATA.meta.statement)} · sin flujo infinito.</small></section><div class="portal-actions"><button data-enter="archive">00 / <strong>excavar</strong>entrar por una pieza fuera del presente</button><button data-enter="present">01 / <strong>abrir ahora</strong>${DATA.present.length} alteraciones seleccionadas</button></div></main>`}
function chrome(content){return `<div class="grain"></div><div class="app-shell"><header class="mast"><button class="sigil" data-action="portal" aria-label="volver al umbral">d</button><div class="wordmark">deriva</div><div class="edition">${safe(DATA.meta.edition)}<br>${String(state.index+1).padStart(2,'0')} : ${String(DATA.present.length).padStart(2,'0')}</div><button class="menu-btn" data-action="system" aria-label="abrir memoria y sistema">⌘</button></header><main id="content" class="viewport">${content}</main>${controls()}</div>${state.sheet?sheet():''}${state.system?system():''}`}
function scene(){const item=current(),p=DATA.present[state.index],archive=state.layer==='archive';return `<article class="scene ${archive?'archive-layer':''}" data-scene><div class="rail" aria-hidden="true">${DATA.present.map((_,i)=>`<i class="${i===state.index?'on':''}"></i>`).join('')}</div><figure class="image-field"><div class="plate" style="--atlas:url('${atlas(item.plate)}');--px:${pos(item.plate).split(' ')[0]};--py:${pos(item.plate).split(' ')[1]}"></div><div class="vignette"></div><span class="ordinal">${archive?'estrato '+String(state.depth+1).padStart(2,'0'):'presente / '+String(state.index+1).padStart(2,'0')}</span><span class="kind">${safe(item.kind||item.status)}</span><span class="symbol">${safe(item.glyph)}</span><figcaption class="image-caption">${archive?'representación propia / atlas deriva':'campo visual local / fuente enlazada en ficha'}</figcaption><span class="depth-mark">${archive?'−':'+'}${archive?state.depth+1:0}</span></figure><section class="copy"><div class="meta"><span>${safe(item.date)}</span><span>${safe(item.source)}</span></div><h1 class="title">${safe(item.title)}</h1><p class="thesis">${safe(item.summary)}</p><button class="read" data-action="read">leer ficha y abrir fuente</button></section></article>`}
function controls(){const archive=state.layer==='archive',saved=state.saved.includes(current()?.id);return `<nav class="controls" aria-label="recorrido"><button class="step" data-action="prev" aria-label="anterior">←</button><button class="traverse" data-action="traverse"><span>${archive?'volver al presente':'excavar'}</span><small>${archive?'misma alteración':'su genealogía'}</small></button><button class="step" data-action="next" aria-label="siguiente">→</button><button class="save ${saved?'active':''}" data-action="save" aria-label="${saved?'retirar de memoria':'guardar en memoria'}">${saved?'●':'○'}</button></nav>`}
function sheet(){if(state.sheet==='install')return `<aside class="sheet" role="dialog" aria-modal="true"><div class="sheet-inner"><div class="sheet-head">instalar deriva<button class="close" data-action="close">×</button></div><h2>añadir al teléfono.</h2><p>En iPhone abre esta página en Safari, toca Compartir, elige “Añadir a pantalla de inicio” y confirma con “Añadir”.</p></div></aside>`;const item=byId(state.sheet);if(!item)return'';const present=DATA.present.find(x=>x.id===item.id);return `<aside class="sheet" role="dialog" aria-modal="true"><div class="sheet-inner"><div class="sheet-head">${safe(item.kind||item.status)} · ${safe(item.date)}<button class="close" data-action="close">×</button></div><h2>${safe(item.title)}</h2><p>${safe(item.summary)}</p>${present?`<p class="reason">por qué entra en deriva — ${safe(present.why)}</p>`:''}<div class="tags">${[...(item.tags||[]),...(item.operations||[])].map(x=>`<span>${safe(x)}</span>`).join('')}</div><a class="origin" href="${url(item.url)}" target="_blank" rel="noopener">abrir fuente primaria o ficha original <span>↗</span></a></div></aside>`}
function system(){const saved=state.saved.map(byId).filter(Boolean);return `<aside class="system" role="dialog" aria-modal="true"><div class="system-inner"><div class="sheet-head">memoria / sistema<button class="close" data-action="system">×</button></div><h2>deriva</h2><section class="system-section"><h3>memoria local · ${saved.length}</h3><div class="memory-list">${saved.length?saved.map((x,i)=>`<button class="memory-row" data-open="${x.id}"><small>${String(i+1).padStart(2,'0')}</small><b>${safe(x.title)}</b><small>${safe(x.kind||'ahora')} ↗</small></button>`).join(''):'<p class="pulse">todavía no has conservado ningún estrato.</p>'}</div></section><section class="system-section"><h3>pulso exterior / sin curaduría</h3><p class="pulse">${safe(state.pulseState)}</p>${state.pulse.slice(0,4).map(x=>`<a class="memory-row" href="${url(x.url)}" target="_blank" rel="noopener"><small>∴</small><b>${safe(x.title)}</b><small>Wikipedia ↗</small></a>`).join('')}</section><section class="system-section"><h3>operación</h3><div class="system-actions"><button data-action="install">instalar</button><button data-action="export">exportar memoria</button><label class="file-action">importar memoria<input id="import-memory" type="file" accept="application/json"></label><button data-action="clear">borrar recorrido</button></div></section><section class="system-section"><h3>criterio</h3><p class="pulse">La edición no ordena por popularidad. Busca alteraciones de percepción, materia, territorio, memoria, transmisión y control. Cada pieza del presente abre una genealogía documental concreta. La sección “pulso exterior” es deliberadamente separada: indica que el mundo siguió moviéndose, pero no entra a la edición sin criterio.</p></section></div></aside>`}
function render(){root.innerHTML=state.portal?portal():chrome(scene());bind();drawField(true)}
function move(dir){if(state.layer==='archive'&&dir>0){const links=DATA.present[state.index].excavate;state.depth=(state.depth+1)%links.length}else{state.index=(state.index+dir+DATA.present.length)%DATA.present.length;state.depth=0}record();render()}
function traverse(){state.layer=state.layer==='present'?'archive':'present';state.depth=0;record();navigator.vibrate?.(9);render()}
async function toggleSave(){const item=current(),i=state.saved.indexOf(item.id);if(i>=0){state.saved.splice(i,1);await dbDelete('saved',item.id);toast('retirado de memoria')}else{state.saved.push(item.id);await dbPut('saved',{id:item.id,at:new Date().toISOString()});toast('conservado en este dispositivo')}render()}
function record(){const item=current();dbPut('history',{key:`${Date.now()}-${item.id}`,id:item.id,layer:state.layer,at:new Date().toISOString()})}
function toast(text){const n=document.createElement('div');n.className='toast';n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.remove(),1500)}
function openSaved(id){const p=DATA.present.findIndex(x=>x.id===id);if(p>=0){state.index=p;state.layer='present'}else{const parent=DATA.present.findIndex(x=>x.excavate.includes(id));if(parent>=0){state.index=parent;state.layer='archive';state.depth=DATA.present[parent].excavate.indexOf(id)}}state.system=false;state.portal=false;render()}
function bind(){root.querySelectorAll('[data-enter]').forEach(b=>b.onclick=()=>{state.portal=false;if(b.dataset.enter==='archive'){state.index=Math.floor(Math.random()*DATA.present.length);state.layer='archive'}else state.layer='present';record();render()});root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openSaved(b.dataset.open));const input=root.querySelector('#import-memory');if(input)input.onchange=importMemory;swipes()}
function act(a){if(a==='portal'){state.portal=true;state.system=false;render()}if(a==='prev')move(-1);if(a==='next')move(1);if(a==='traverse')traverse();if(a==='save')toggleSave();if(a==='read'){state.sheet=current().id;render()}if(a==='close'){state.sheet=null;render()}if(a==='system'){state.system=!state.system;render()}if(a==='install'){state.system=false;state.sheet='install';render()}if(a==='export')exportMemory();if(a==='clear'){openDB().then(d=>{['history','prefs'].forEach(s=>d.transaction(s,'readwrite').objectStore(s).clear())});toast('recorrido borrado')}}
function swipes(){const el=root.querySelector('[data-scene]');if(!el)return;let sx=0,sy=0;el.ontouchstart=e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY};el.ontouchend=e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.4)move(dx<0?1:-1);else if(Math.abs(dy)>65&&Math.abs(dy)>Math.abs(dx)*1.4)traverse()}}
function exportMemory(){const data={schema:4,exportedAt:new Date().toISOString(),saved:state.saved};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download='deriva-memoria.json';a.click();URL.revokeObjectURL(u)}
async function importMemory(e){try{const j=JSON.parse(await e.target.files[0].text());if(!Array.isArray(j.saved))throw Error();for(const id of j.saved.filter(byId)){if(!state.saved.includes(id))state.saved.push(id);await dbPut('saved',{id,at:new Date().toISOString()})}toast('memoria incorporada');state.system=false;render()}catch{toast('archivo no válido')}}
async function livePulse(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');try{const r=await fetch(`https://es.wikipedia.org/api/rest_v1/feed/featured/${y}/${m}/${day}`),j=await r.json(),news=j.news||[];state.pulse=news.map(x=>({title:(x.titles?.normalized||x.title||'').replace(/_/g,' '),url:x.content_urls?.desktop?.page||x.content_urls?.mobile?.page||'#'})).filter(x=>x.title);state.pulseState=state.pulse.length?`señales registradas el ${day}.${m}.${y}; no forman parte de la edición hasta ser revisadas.`:'no llegaron señales externas para esta fecha.'}catch{state.pulseState='sin conexión exterior; la edición y el archivo siguen disponibles.'}if(state.system)render()}
function drawField(reset=false){const dpr=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;if(reset||canvas.width!==w*dpr){canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}const seed=state.index*31+(state.layer==='archive'?17:3),points=Array.from({length:13},(_,i)=>({x:((i*97+seed*19)%101)/101*w,y:((i*53+seed*29)%103)/103*h}));ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(231,225,214,.22)';ctx.lineWidth=.5;points.forEach((p,i)=>{const q=points[(i*5+3)%points.length];ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()});ctx.fillStyle='rgba(231,225,214,.55)';points.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,i%4?1:2.3,0,Math.PI*2);ctx.fill()})}
addEventListener('resize',()=>drawField(true));addEventListener('keydown',e=>{if(e.key==='Escape'&&(state.sheet||state.system)){state.sheet=null;state.system=false;render()}if(!state.portal&&e.key==='ArrowRight')move(1);if(!state.portal&&e.key==='ArrowLeft')move(-1);if(!state.portal&&['ArrowUp','ArrowDown'].includes(e.key))traverse()});
async function init(){state.saved=(await dbAll('saved')).map(x=>x.id).filter(byId);render();livePulse();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(reg=>reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)toast('nueva edición lista · recarga')})})).catch(()=>{})}
init();
})();
